import postgres from 'postgres';

// Creates the Better Auth (SIWE) tables. Mirrors src/auth-schema.ts, which is
// generated by `bun run auth:generate` in apps/web. Run after the core migration.
const connectionString =
  process.env.DATABASE_URL || 'postgresql://hyperdash:hyperdash_password@localhost:5432/hyperdash';

async function runAuthMigrations() {
  console.log('Starting Better Auth migrations...');
  const client = postgres(connectionString, { max: 1 });

  try {
    await client`
      CREATE TABLE IF NOT EXISTS "user" (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        email TEXT NOT NULL UNIQUE,
        email_verified BOOLEAN NOT NULL DEFAULT FALSE,
        image TEXT,
        created_at TIMESTAMP NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMP NOT NULL DEFAULT NOW()
      )
    `;

    await client`
      CREATE TABLE IF NOT EXISTS "session" (
        id TEXT PRIMARY KEY,
        expires_at TIMESTAMP NOT NULL,
        token TEXT NOT NULL UNIQUE,
        created_at TIMESTAMP NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMP NOT NULL,
        ip_address TEXT,
        user_agent TEXT,
        user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE
      )
    `;
    await client`CREATE INDEX IF NOT EXISTS session_userId_idx ON "session"(user_id)`;

    await client`
      CREATE TABLE IF NOT EXISTS "account" (
        id TEXT PRIMARY KEY,
        account_id TEXT NOT NULL,
        provider_id TEXT NOT NULL,
        user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
        access_token TEXT,
        refresh_token TEXT,
        id_token TEXT,
        access_token_expires_at TIMESTAMP,
        refresh_token_expires_at TIMESTAMP,
        scope TEXT,
        password TEXT,
        created_at TIMESTAMP NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMP NOT NULL
      )
    `;
    await client`CREATE INDEX IF NOT EXISTS account_userId_idx ON "account"(user_id)`;

    await client`
      CREATE TABLE IF NOT EXISTS "verification" (
        id TEXT PRIMARY KEY,
        identifier TEXT NOT NULL,
        value TEXT NOT NULL,
        expires_at TIMESTAMP NOT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMP NOT NULL DEFAULT NOW()
      )
    `;
    await client`CREATE INDEX IF NOT EXISTS verification_identifier_idx ON "verification"(identifier)`;

    await client`
      CREATE TABLE IF NOT EXISTS "wallet_address" (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
        address TEXT NOT NULL,
        chain_id INTEGER NOT NULL,
        is_primary BOOLEAN DEFAULT FALSE,
        created_at TIMESTAMP NOT NULL
      )
    `;
    await client`CREATE INDEX IF NOT EXISTS "walletAddress_userId_idx" ON "wallet_address"(user_id)`;

    console.log('✅ Better Auth migrations completed successfully!');
  } catch (error) {
    console.error('❌ Better Auth migration failed:', error);
    throw error;
  } finally {
    await client.end();
  }
}

if (require.main === module) {
  runAuthMigrations()
    .then(() => process.exit(0))
    .catch(() => process.exit(1));
}

export { runAuthMigrations };
